[FIXED] [#68] AutoValue builder constaint issue. Added `@Nullable` and `@NonNull` to address strict rule.
Was crashing with following:

```
E/HeadlinesPresenter: Failed to load responses.
                      java.lang.IllegalStateException: Missing required properties: category cards
                          at info.hossainkhan.android.core.model.AutoValue_NavigationRow$Builder.build(AutoValue_NavigationRow.java:161)
```