[FIXED] [#68] Marked title as nullable as well, since divider type does not required title.
Was crashing with following:

```
E/HeadlinesPresenter: Failed to load responses.
                      java.lang.IllegalStateException: Missing required properties: title
                          at info.hossainkhan.android.core.model.AutoValue_NavigationRow$Builder.build(AutoValue_NavigationRow.java:160)
                          at info.hossainkhan.dailynewsheadlines.utils.LeanbackHelper.buildNavigationDivider(LeanbackHelper.java:64)
                          at info.hossainkhan.dailynewsheadlines.utils.LeanbackHelper.addSettingsNavigation(LeanbackHelper.java:79)
                          at info.hossainkhan.dailynewsheadlines.browser.HeadlinesBrowseFragment.applyStaticNavigationItems(HeadlinesBrowseFragment.java:182)
                          at info.hossainkhan.dailynewsheadlines.browser.HeadlinesBrowseFragment.loadRows(HeadlinesBrowseFragment.java:162)
                          at info.hossainkhan.dailynewsheadlines.browser.HeadlinesBrowseFragment.showHeadlines(HeadlinesBrowseFragment.java:127)
                          at info.hossainkhan.android.core.headlines.HeadlinesPresenter$2.onNext(HeadlinesPresenter.java:154)
```